### ISSUE TITLE
Unable to run pod in Kubernetes

### ISSUE THREAD

**Issue by gcpguru** [adaptant-labs/ncs2-device-plugin#1]
When the pod starts up, it immediately fails with the following: 

Traceback (most recent call last):
  File "/usr/local/bin/ncs2_device_plugin", line 11, in <module>
    load_entry_point('ncs2-device-plugin==0.2.0', 'console_scripts', 'ncs2_device_plugin')()
  File "/app/ncs2_device_plugin/main.py", line 46, in main
    server = NCS2DevicePluginServer(service=service, logger=logger)
  File "/app/ncs2_device_plugin/server.py", line 25, in __init__
    self.server.add_insecure_port('unix://' + ncs2_socket_path)
  File "/usr/local/lib/python3.8/dist-packages/grpcio-1.34.0-py3.8-linux-x86_64.egg/grpc/_server.py", line 961, in add_insecure_port
    return _common.validate_port_binding_result(
  File "/usr/local/lib/python3.8/dist-packages/grpcio-1.34.0-py3.8-linux-x86_64.egg/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: **Failed to bind to address unix:///var/lib/kubelet/device-plugins/ncs2.sock**

Complete log file attached. 
[failed_pod.log](https://github.com/adaptant-labs/ncs2-device-plugin/files/6069819/failed_pod.log)

**Comment by pmundt** [comment]
Thanks for the report @rafaeljcuevas. Can you try re-run this with `GRPC_VERBOSITY=debug` set so we can figure out why the socket file is not being created?

Also, are you using a specific Kubernetes version or distribution?
